### ISSUE TITLE
Label mapping Error

### ISSUE THREAD

**Issue by xhay-p** [gstoica27/Re-TACRED#1]
Hello,

I am trying to run PALSTM model following the instruction, but while loading the dataset, I ran into a `KeyError: 'org:city_of_branch`.

Some implementation details:
1.  I have created the new dataset by applying the patch. 
2. I am using the new dataset.
3. I have all the necessary files in place from TACRED's repository.

I believe there is some inconsistency in utils/constant `LABEL_TO_ID` dictionary. Could you please help me resolve the issue.

**Comment by gstoica27** [comment]
Oh whoops! I forgot to change the "org:*_of_headquarters" --> "org:*_of_branch" where "*" is a city/state/province/country in the [MODEL]/utils/constant.py files. 

Like you stated, this issue is occurring because the data preprocessing function is mapping data instance attributes to indices using hardcoded mappings stored in the constant.py file, and there was a mixup between the two. 

Sorry about that. I've made the corrections so now it should run hopefully!
